### ISSUE TITLE
Template validation fails for aws-vpc

### ISSUE THREAD

**Issue by davdunc** [aws-quickstart/quickstart-aws-vpc#43]
### Issue
Attempts to validate the aws-vpc.template.yaml  fails to validate. 
Template is too long to be used from local resources. 

### Response
```
fatal: [localhost]: FAILED
[. . . ] 
Name: !Sub '${AWS::StackName}-VPCID'", "' at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200"]
```
### Expected 
Validation status okay. 
### Steps to Reproduce
Ansible reproducer: 

``` yaml
---
- name: Test building the VPC configuration
  hosts: localhost
  connection: local

  vars:
    aws_region: us-east-1
    aws_profile: default

  tasks:
    - name: download the current template for APN Quick Start for VPC
      get_url:
        url: https://raw.githubusercontent.com/aws-quickstart/quickstart-aws-vpc/main/templates/aws-vpc.template.yaml
        dest: files/aws-vpc.template.yaml
        mode: '0750'
    - name: Validate the current template for APN Quick Start for VPC
      command:
        argv:
          - aws
          - cloudformation
          - validate-template
          - --template-body
          - file://files/aws-vpc.template.yaml
      register: cf_vpc_validation
```
